# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: cocofest
channels:
- conda-forge
dependencies:
- biorbd
- bioviz
- python-graphviz
- pyqtgraph
- pyorerun
